LIST p=16F628A
#include <p16F628A.inc>
__CONFIG _INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_ON & _MCLRE_OFF & _BODEN_ON & _LVP_OFF & _CP_OFF
CBLOCK 0x20

    W_TEMP
    STATUS_TEMP
ENDC
#define S1 4
#define S2 5
#define S3 6
#define S4 7
#define SIREN 0
#define GAZ   1
ORG 0x000
GOTO BASLAT
ORG 0x004
GOTO KESME
ORG 0x010
KESME
    MOVWF W_TEMP
    SWAPF STATUS,W
    MOVWF STATUS_TEMP
    BTFSS INTCON,RBIF
    GOTO KESME_BITIR
    MOVF PORTB,W
    BCF INTCON,RBIF
    ANDLW b'11110000'
    BTFSC STATUS,Z
    GOTO ALARM_KAPAT
    GOTO ALARM_AKTIF
 ALARM_KAPAT
    BCF PORTA,SIREN
    BCF PORTA,GAZ
    GOTO KESME_BITIR
ALARM_AKTIF
    BSF PORTA,SIREN
    BSF PORTA,GAZ
    GOTO KESME_BITIR
KESME_BITIR
    SWAPF STATUS_TEMP,W
    MOVWF STATUS
    SWAPF W_TEMP,F
    SWAPF W_TEMP,W
    RETFIE
BASLAT
    BSF STATUS,RP0
    MOVLW b'11111100'
    MOVWF TRISA
    MOVLW b'11110000'
    MOVWF TRISB
    MOVLW b'10000000'
    MOVWF OPTION_REG
    BCF STATUS,RP0
    CLRF PORTA
    MOVF PORTB,W
    BSF INTCON,RBIE
    BSF INTCON,GIE

ANA_DONGU

    GOTO ANA_DONGU

END